# Generated by Django 6.0.6 on 2026-06-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_ratesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('pc_count', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cloth', models.CharField(blank=True, max_length=100)),
                ('mtr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inv_no', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitchings', to='invoices.tailor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
